### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by PigCharid** [clxyder/walletconnect-expo-example#10]
[Unhandled promise rejection: Error: Mobile registry not yet ready.]
at http://192.168.101.241:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:161817:37 in connect$
at node_modules/@walletconnect/react-native-dapp/dist/providers/WalletConnectProvider.js:192:29 in Object.assign$argument_1.connect
at screens/TabOneScreen.tsx:20:24 in TabOneScreen
at node_modules/react-native/Libraries/Pressability/Pressability.js:697:17 in _performTransitionSideEffects
at node_modules/react-native/Libraries/Pressability/Pressability.js:634:6 in _receiveSignal
at node_modules/react-native/Libraries/Pressability/Pressability.js:528:8 in responderEventHandlers.onResponderRelease

**Comment by clxyder** [comment]
Hey @PigCharid, this repo is quite outdated so there may be some discrepancies with the newer libraries.
